# Generated by Django 5.1.7 on 2025-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.AddField(
            model_name="message",
            name="sender_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
