# Generated by Django 5.1.7 on 2025-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_message_sender_message_sender_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_phone",
            field=models.CharField(max_length=15),
        ),
    ]
